# Header
menu:
  Home: /
  Blog: /blog

# Read More text
excerpt_link: Read More

# Widgets List
widgets:
  tags: true

homepage_post_title: homepage

gallery_max_height: 100px
gallery_max_width: 100px
